import {
  ArrowRight,
  Apple,
  BookOpen,
  CalendarDays,
  CalendarRange,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronLeft,
  ChevronRight,
  Copy,
  Coffee,
  ClipboardPaste,
  ChefHat,
  DatabaseBackup,
  Download,
  Droplets,
  Dumbbell,
  Flame,
  Gauge,
  GripVertical,
  ListPlus,
  Leaf,
  NotebookTabs,
  Pencil,
  Plus,
  Save,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Target,
  Trash2,
  UserRound,
  Utensils,
  Moon,
  WandSparkles,
  Weight,
  Wheat,
  X,
  createIcons,
} from "lucide";

const ICONS = {
  ArrowRight,
  Apple,
  BookOpen,
  CalendarDays,
  CalendarRange,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronLeft,
  ChevronRight,
  Copy,
  Coffee,
  ClipboardPaste,
  ChefHat,
  DatabaseBackup,
  Download,
  Droplets,
  Dumbbell,
  Flame,
  Gauge,
  GripVertical,
  ListPlus,
  Leaf,
  NotebookTabs,
  Pencil,
  Plus,
  Save,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Target,
  Trash2,
  UserRound,
  Utensils,
  Moon,
  WandSparkles,
  Weight,
  Wheat,
  X,
};

export type IconName = keyof typeof ICONS;

export const icon = (name: IconName, className = ""): string =>
  `<i data-lucide="${name}" class="icon ${className}" aria-hidden="true"></i>`;

export const renderIcons = (root: HTMLElement): void => {
  createIcons({
    icons: ICONS,
    root,
    attrs: { "aria-hidden": "true", "stroke-width": "1.8" },
  });
};
